config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pages.urls')),
    path('post/', include('posts.urls'),)

]

pages/urls.py
from django.urls import path
from .views import HomePageView, AboutPageView

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('about', AboutPageView.as_view(), name='about'),
]

posts/urls.py
from django.urls import path
from .views import *

app_name = 'posts'

urlpatterns = [
    path('', HomePageView.as_view(), name='home_p'),
]

pages/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models

class Post(models.Model):
    text = models.TextField()

    def __str__(self) -> str:
        return self.text[:25]

pages/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

class HomePageView(TemplateView):
    template_name = 'home.html'

class AboutPageView(TemplateView):
    template_name='about.html'

posts/views.py
from django.shortcuts import render
from .models import Post
from django.views.generic import ListView

class HomePageView(ListView):
    model = Post
    template_name ='home_p.html'
    context_object_name = 'all_post_list'

pages/templates/pages/about.html
{% extends 'base.html' %}

{% block content %}
<h1>About page</h1>
{% endblock content %}

pages/templates/pages/base.html
<header>
    <a href="{% url 'home' %}">Home</a>
    <a href="{% url 'about' %}">About</a>
    <a href="{% url 'posts:home_p' %}">Posts</a>
</header>
{% block content %}
{%endblock%}

pages/templates/pages/home.html
{% extends "base.html" %}

{% block content %}
<h1>Homepage</h1>
{% endblock %}

posts/templates/post/home_p.html
<h1>Message board homepage</h1>
<ul>
    {% for p in all_post_list %}
    <li>{{ p.text }}</li>
    {% endfor %}
</ul>